-- Run in Supabase SQL editor.

-- 1) Storage bucket (public = false)
insert into storage.buckets (id, name, public)
values ('scan-olny', 'scan-olny', false)
on conflict (id) do nothing;

-- 2) Metadata table for uploaded files
create table if not exists public.cloud_documents (
  id bigint generated by default as identity primary key,
  local_id bigint not null,
  user_id uuid not null,
  name text not null,
  scan_type text not null,
  file_type text not null,
  file_size_mb double precision not null default 0,
  cloud_path text not null,
  updated_at timestamptz not null default now()
);

alter table public.cloud_documents enable row level security;

-- 3) RLS policies for metadata table
drop policy if exists "cloud_documents_select_own" on public.cloud_documents;
create policy "cloud_documents_select_own"
on public.cloud_documents
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "cloud_documents_insert_own" on public.cloud_documents;
create policy "cloud_documents_insert_own"
on public.cloud_documents
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "cloud_documents_update_own" on public.cloud_documents;
create policy "cloud_documents_update_own"
on public.cloud_documents
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 4) Storage object RLS policies (bucket: scan-olny)
drop policy if exists "scan_only_read_own" on storage.objects;
create policy "scan_only_read_own"
on storage.objects
for select
to authenticated
using (bucket_id = 'scan-olny' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "scan_only_insert_own" on storage.objects;
create policy "scan_only_insert_own"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'scan-olny' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "scan_only_update_own" on storage.objects;
create policy "scan_only_update_own"
on storage.objects
for update
to authenticated
using (bucket_id = 'scan-olny' and auth.uid()::text = (storage.foldername(name))[1])
with check (bucket_id = 'scan-olny' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "scan_only_delete_own" on storage.objects;
create policy "scan_only_delete_own"
on storage.objects
for delete
to authenticated
using (bucket_id = 'scan-olny' and auth.uid()::text = (storage.foldername(name))[1]);
